canonical/dqlite

- driver.go
- http_test.go
- log.go
- log_test.go
- testdata/demo.go
Migrate existing code to use LevelFilterWithOrigin instead of
NewLogger.
> Integrate LevelFilterWithOrigin

- testdata/demo.go
Extract the logic of main() into shorter fuctions, for readability.
> Refactor the main() function of the demo into smaller units.

- internal/transaction/txn.go
This seems something that can happen under some circumstances, and it
should be idempotent.
> Allow Started->Started txn state transition

- include/dqlite.h
- src/stmt.c
- test/test_stmt.c
This oriented to language like Go that have a native boolean type.
> Add a new DQLITE_BOOLEAN datatype

- .travis.yml
- Makefile.am
- configure.ac
- src/lifecycle.c
- src/lifecycle.h
- src/replication.c
- src/replication.h
- src/vfs.c
- test/runner.c
- test/test_message.c
- test/test_replication.c
Stub for the dqlite C implementation of the SQLite replication interface.
> Initial dqlite implementation of the SQLite replication interface

- src/tuple.c
Fixes https://github.com/lxc/lxd/issues/5884
> Calculate the correct header size when there are exactly 8 params

- src/vfs.c
Signed-off-by: Cameron Nemo <cnemo@tutanota.com>
> fix(vfs): include pthread.h for musl compat

- src/replication.c
See https://github.com/lxc/lxd/issues/6322.
> Improve error message when a raft transaction is too large

- src/server.c
> Use SOCK_CLOEXEC when creating the listening socket

- src/lib/serialize.h
> Fix encoding of blob len on 32bit

- include/dqlite.h
- src/config.c
- src/config.h
- src/gateway.c
- src/server.c
- src/server.h
- src/transport.c
- src/transport.h
> Properly support 64 bit node IDs

- src/server.c
- src/vfs.c
> Drop unnecessary vfs mutex

- test/unit/test_conn.c
- test/unit/test_vfs.c
Signed-off-by: Free Ekanayaka <free.ekanayaka@canonical.com>
> Fix flaky tests

- include/dqlite.h
- src/dqlite.c
- src/format.c
- src/format.h
- src/leader.c
- src/vfs.c
- src/vfs.h
- test/integration/test_vfs.c
- test/lib/heap.c
- test/unit/test_vfs.c
This can be used to take a full snapshot of a database with VFS V2.
> Add dqlite_vfs_snapshot() api

- src/leader.c
Also when using VFS v2 the `leaderApplyFrames()` function should keep track of in-flight raft requests, so their result can be ignored if the client aborts before the result.
> leader: Keep track of inflight exec requests to clean them up on close

- src/leader.c
> Fix 'main' is usually a function warning

- README.md
A couple of corrections that I missed on my first read through.
> Grammatical changes

- src/gateway.c
- src/server.c
> Style fix: spaces to tabs indent

- src/server.c
In file included from /usr/include/string.h:495,
from /usr/include/x86_64-linux-gnu/sys/un.h:37,
from src/server.c:4:
In function ‘strncat’, inlined from ‘dqlite_node_set_bind_address’ at src/server.c:225:4:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10:
warning: ‘__builtin___strncat_chk’ specified bound 107 equals destination size [-Wstringop-truncation]
136 |   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10:
warning: ‘__builtin___strncat_chk’ specified bound 107 equals
destination size [-Wstringop-overflow=]
> server.c: Fix strncat warning

- src/vfs.c
- test/integration/test_vfs.c
Fixes https://github.com/canonical/dqlite/issues/292.
@freeekanayaka you have an idea how I could fit this in the test suite? https://www.sqlite.org/c3ref/test_control.html can be used to adapt the `pending_byte` value but it is not a stable API, so am a bit reluctant to use it.
> vfs: Allow skipping a page when writing past PENDING_BYTE

- configure.ac
> Release v1.7.0

- include/dqlite.h
- src/server.c
- test/integration/test_node.c
> node: Expose raft snapshot settings

- Makefile.am
- include/dqlite.h
- src/gateway.c
- src/server.c
- src/translate.c
- src/translate.h
- src/utils.h
- test/integration/test_node.c
Add v2 of recover command that includes the server roles.
> Recover v2

- include/dqlite.h
- src/server.c
- test/integration/test_node.c
Fixes https://github.com/canonical/dqlite/issues/286.
> server: Add dqlite_set_network_latency_ms to API

- src/leader.c
- src/tracing.h
- src/vfs.c
Added nanoseconds timestamp to trace and added some more traces, especially during lock contention.
> Add timestamp to trace

- .github/workflows/packages.yml
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> github: Add package builds

- AUTHORS
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> AUTHORS: Update to refer to git

- src/client.c
- src/command.c
- src/conn.c
- src/format.c
- src/fsm.c
- src/lib/queue.h
- src/lib/serialize.h
- src/vfs.c
- test/unit/test_gateway.c
- test/unit/test_tuple.c
Mostly string format fixes, integer comparison fixes & telling the compiler that the pointer alignments are fine.
> Build fixes armhf impish

- src/command.c
> command: Initialize header

- README.md
closes https://github.com/canonical/dqlite/issues/339
> README: Update Install section

- .github/workflows/build-and-test.yml
- .github/workflows/coverity.yml
- README.md
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> Update for new PPA

- src/server.c
- src/server.h
> server: remove unused mutex

- src/gateway.c
- src/transport.c
> gateway: transport: Initialize stack variables

- src/lib/util.h
- src/tracing.h
Optimization for all the trace calls in the code.
> util: Define and use likely/unlikely macros

- README.md
See https://github.com/canonical/raft/issues/228.
> README: note AIO requirement

- src/gateway.c
> gateway: Fix uint64_t to size_t db_id conversion.

- .github/workflows/build-and-test.yml
> github actions: codecov v2 -> v3

- src/db.c
- src/leader.c
From the SQLite [docs](https://www.sqlite.org/c3ref/open.html) on `sqlite3_open_v2`
A database connection handle is usually returned in *ppDb, even if an error occurs. The only exception is that if SQLite is unable to allocate memory to hold the sqlite3 object, a NULL will be written into *ppDb instead of a pointer to the sqlite3 object.
Whether or not an error occurs when it is opened, resources associated with the database connection handle should be released by passing it to `sqlite3_close()` when it is no longer required.
> db/leader: Cleanup after sqlite3_open_v2

- src/vfs.c
Fixes some coverity issues introduced by merging the disk-mode PR.
> Coverity disk

- src/fsm.c
Fixes 32bit build. 
There's a deeper issue in the raft snapshot restore API that limits the database size to what fits in a single buffer of `size_t` bytes.
This would need to be fixed in a separate PR as it requires more thorough work.
> fsm: Explicitly cast uint64_t to size_t

- configure.ac
- test/unit/test_conn.c
- test/unit/test_gateway.c
- test/unit/test_replication.c
This PR will be needed to fix the tests once https://github.com/canonical/raft/pull/336 is merged.
> Test fixes following raft quorum bugfix.

- .github/workflows/packages.yml
> packages: remove bionic, impish; add kinetic

- src/conn.c
> conn: Fix handling of request.words

- .github/workflows/build-and-test.yml
> github: Remove deprecated Ubuntu Bionic

- src/client/protocol.c
- src/client/protocol.h
- src/conn.c
- src/gateway.c
- src/gateway.h
- src/protocol.h
- src/response.h
- test/lib/client.h
- test/unit/test_concurrency.c
- test/unit/test_conn.c
- test/unit/test_gateway.c
> gateway: Error when prepared SQL has ignored tail

- src/gateway.c
- test/unit/test_gateway.c
> gateway: Fix handling of statements with trailing whitepace, comments

- src/client/protocol.c
- src/client/protocol.h
That is, instead of tracking a *duration* that upper-bounds the time we spend waiting in poll(2), we track an *instant* and return early if that instant has passed when we're about to poll. This is how Go does it, and for good reason: with the duration-based approach, it's impractical to track time that elapses while doing things other than polling for socket readiness (or waiting for some other blocking syscall to complete). I realized that this is important while working on #480, which needs to call these client functions in an asynchronous context where lots of other stuff is going on besides client/server message exchange.
> client/protocol: Switch context from budget to deadline

- src/gateway.c
- test/unit/test_gateway.c
> gateway: Special-case SQLITE_ROW as error return

- src/server.c
The previous code would behave incorrectly when reading an info file or node store with a size too large to be represented by ssize_t. (This is only possible on 32-bit systems, and indeed a build failure on armhf on Launchpad was what pointed me to the bug.)
> server: Fix overflow issue with return of lseek

- include/dqlite.h
> Adjust the dqlite client API surface

- src/bind.c
- src/gateway.c
- src/tuple.c
- test/unit/test_concurrency.c
- test/unit/test_conn.c
- test/unit/test_gateway.c
- make the test suite compile
- fix bugs as result of running the tests
> Fix tests to accept db_context

- .github/workflows/packages.yml
> Only publish to the PPA from master

- README.md
- src/lib/byte.h
- src/tracing.c
- src/tracing.h
- Removed static qualifier from tracef() to fix potential multithreading bug;
- Added log levels.
> Initial log format rework

- .github/workflows/downstream.yml
> downstream: Fix repo references.

- .github/workflows/downstream.yml
> downstream: Fix another ref.

- .github/workflows/build-and-test.yml
This reverts commit 1e177120c59a1ad3f8a76a108555e440b7d9c124.
> Revert "build(deps): bump codecov/codecov-action from 3 to 4"

- Makefile.am
Another bug introduced when I refactored Makefile.am for #568.
> Fix --enable-build-sqlite

- configure.ac
> Bump libuv version requirement to 1.34

- .github/workflows/build-and-test.yml
Taking another swing at the flaky tests.
> Build concurrently, test serially

- CODE_OF_CONDUCT.md
> Add a link to the Ubuntu Code of Conduct

- src/raft/uv_list.c
I have checked that `uv_fs_req_cleanup` correctly cleans up the resources because when adding:
```c
uv_fs_scandir(NULL, &req, uv->dir, 0, NULL);
return rv;
```
the test fail (with ASAN on) because of a memory leak. But when doing:
```c
uv_fs_scandir(NULL, &req, uv->dir, 0, NULL);
uv_fs_req_cleanup(&req);
return rv;
```
all the tests passed, which means that it correctly deallocates the resources associated with the request.
I have also simplified the flow of the function as much as possible.
> bugfix: reading segment, correctly stop on error

- src/conn.c
- src/conn.h
- src/gateway.c
- src/gateway.h
- src/leader.c
- src/leader.h
- test/integration/test_client.c
- test/unit/test_concurrency.c
- test/unit/test_gateway.c
This reverts #687 in response to regressions seen by LXD e.g. [here](https://github.com/canonical/lxd/actions/runs/10585686970/job/29332853243).
> Revert "Merge pull request #687 from cole-miller/exec-sql-suspend-v2"

- .github/workflows/packages.yml
> PPA: remove mantic and add oracular

- .github/workflows/packages.yml
Footgun due to not using actions/checkout
> Fix packages workflow

- .github/workflows/cla-check.yml
> chore: update CLA check job

- src/gateway.c
This PR moves the order of the methods in `gateway.c` so that they are semantically close. The aim of this PR is to improve patch readability for #740 .
It also removes usage of `sqlite3_{malloc,free}` for RAFT related operations in favour of `raft_{malloc,free}`.
Last, it also includes an improved version of `START_V0` that can now omit the response, in case it's not needed. This removes all the awkward `(void)response;` in the code.
> chore: improve gateway readability

- src/raft/uv_os.c
This PR tries again to call `posix_fallocate` in case the system call was interrupted by a signal.
> fix: retry fallocate if EINTR is returned

- .github/workflows/build-and-test.yml
This PR fixes the pipeline *for the LTS branch*.
> chore: fix test pipeline

- .github/workflows/build-and-test.yml
- src/fsm.c
This PR fixes a small build issue introduced lately and adds build testing on all published platforms in the PPA.
Closes #412.
> chore: test building on all enable architectures

- src/raft/uv_fs.c
- test/raft/unit/test_compress.c
This PR fixes a regression in tests caused by #804 .
> fix: fix compression test and explicit assumption
