replication/methods.go
testdata/demo.go

When the leader loses leadership just before running the WalFrames
replication hook (typically to commit a transaction), it now properly
marks the transaction as stale (so the automatic WAL rollback
initiated by SQLite will effectively be a no-op) and start a surrogate
follower (so the next leader can roll back the leftover transaction
that it finds).
Also, the demo program has been changed to handle tx.Commit() failures
differently: in that case there's no need to call tx.Rollback(), as
that is automatically handled by SQLite.
Fixes #2.

Fix leadership lost just before the WalFrames replication hook

---

driver.go

This avoids the issue of a leader connection being open too early,
before leadership is actually acquired, and fixes #5.

Make clients block on leadership in db.Open instead of conn.Begin

---

.dir-locals.el
log.go
log_test.go
testdata/demo.go

The new LevelFilterWithOrigin type extends Hashicorp's LevelFilter by
also supporting filtering by "origin", which is an additional string
following the level.

Add LevelFilterWithOrigin log filter

---

replication/fsm.go
replication/fsm_test.go

They were disabled after the switch to protobuf, which changed the API
of the command subpackage.

Re-enable FSM-related unit tests

---

driver.go
run-demo

This makes life a bit easier for consumer libraries, since running
queries on the leader only is the typical use case.

Make all driver.Driver-related APIs check if we're the leader

---

.travis.yml
driver.go
integration_test.go

Since gating dqlite behind gRPC SQL is a common use case, an
integration test has been added, which also exemplifies how to wire
things together.

Add integration test with go-grpc-sql

---

.travis.yml
driver.go

It was ignored before.
Also, make dqlite.Conn implement the Execer interface.

Make AutoCheckpoint actually set the Driver option

---

driver.go

This gives a clear hint to consumer to retry whatever they were doing
against another node.

Return ErrNotLeader if the barrier fails because leadership was lost

---

integration_test.go
internal/replication/fsm_test.go
internal/replication/methods.go
internal/transaction/registry.go
internal/transaction/registry_test.go
internal/transaction/txn_test.go

Since for some reason sqlite doesn't seem to serialize the pager
transactions, this commit does that inside dqlite itself.

Serialize transactions started by different leader connections

---

.travis.yml
ci/download-sqlite.sh
internal/replication/integration_test.go

This uses the new raft-test API to make the snapshot integration test less
flaky.

Fix snapshot integration tests

---

src/conn.c
src/conn.h
src/server.c

The current uv_is_closing((uv_handle_t *)(&c->stream)) check is
dqlite__conn_abort() doesn't seem to be effective enough, and probably
uv_is_closing() sometimes returns 0 even if we already called uv_close().
A new conn->aborting attribute has been added to track the connection state
internally in dqlite.

Fix race in the connection abort sequence

---

src/gateway.c
src/schema.h
src/server.c
test/cluster.c
test/test_gateway.c
test/test_schema.c

This leaves the dqlite_cluster implementation itself free to release the memory it
returns.

Copy dynamic data returned by the configured dqlite_cluster implementation

---

src/conn.c
src/server.c

The initialization was previously in dqlite_server_create, which leaks a file
descriptor in case the server is destroyed before it's even run.

Initialize the UV loop object in dqlite_server_run

---

src/conn.c
test/test_conn.c
test/test_queue.c

The reason is that the close callback for the stream handle also releases the
memory of the connection object, which holds the timer handle as well. Since
libuv has some handle-involving logic triggering after uv_close(), even in the
case where the close callback is set to NULL, the previous code could result in
invalid memory accesses.

Close the connection stream handle after the timer one

---

Makefile.am
src/vfs.c
test/fs.c
test/fs.h
test/test_vfs.c

Apparently this might happen in SQLite when opening a database.

Allow releasing a shared-memory lock before acquiring it.

---

include/dqlite.h
src/conn.c
src/conn.h
src/gateway.c
src/gateway.h
src/replication.h
src/schema.h
src/stmt.c
test/case.c
test/test_gateway.c
test/test_schema.c

This is in preparation of non-blocking write requests that need to go through
raft.

Make dqlite__gateway's API asynchronous

---

.clang-format
include/dqlite.h
src/conn.c
src/conn.h
src/gateway.c
src/gateway.h
src/message.c
src/message.h
src/schema.h
src/stmt.c
src/stmt.h
test/client.c
test/runner.c
test/socket.c
test/socket.h
test/test_conn.c
test/test_integration.c
test/test_queue.c
test/test_stmt.c

This reduces latency as clients can get the first batch for rows right away (and
possibly decide to interrupt the query).

Split large result queries in multiple responses

---

src/db.c
src/db.h
src/gateway.c

This gives user code a chance to clean up per-db state.

Call the xUnregister method of dqlite_cluster when closing a database

---

src/db.c
src/db.h
src/gateway.c
src/gateway.h
test/test_gateway.c

This simplifies a bit the code and the logic that will come. For now there is no
need to support multiple databases per connection, however if that ever becomes
necessary the protocol still requires the client to pass a database ID a
parameter for requests.

Allow opening at most one database per connection

---

Makefile.am
test/case.c
test/runner.c
test/socket.c
test/socket.h
test/test_uv.c

Tests that read and write callbacks fire synchronously when the buffer size is small and the stream is an abstract Unix sockets or a loopback TCP connection.

Add libuv-related tests

---

src/stmt.c
test/test_stmt.c

Disable splitting large queries in multiple responses

---

src/gateway.c
src/server.c

It turns out that this is necessary in order to avoid SQLite considering the
statement still in progress, and returning SQLITE_BUSY upon subsequent API
calls.
Closes #92.

Reset prepared statements upon failures

---

src/format.h
src/gateway.c
test/test_gateway.c
test/test_vfs.c

The offset value should be equal to the read mark array index plus 3, which is
where read locks start.
This fixes a failure noticed in LXD, see https://github.com/lxc/lxd/issues/5249.

Fix the value of the offset passed to xShmLock when checking for read locks

---

doc/faq.md

The latest rename of this operating system happened in 2016.
This also fixes a missing word immediately below.

Change reference to OS X to macOS

---

src/protocol.h
src/query.c

The column types are return as defined by the user, so if it was done lowercase it won't match -- this change fixes that.
Also added a DQLITE_ISODATE type to mark the column as being a date only (not a timestamp).

Case-insensitive column type lookups, DATE support

---

doc/protocol.md

The protocol client message numbers 0, 1, 3 and were repeated; this cleans it up.

remove duped client messages

---

src/vfs.c

vfs__delete_contents would unlock the passed &root->mutex, but all of
its callers would then also unlock the passed &root->mutex. It turns out
that this works on most architectures without issue, but [apparently][1] on
[some Intel CPUs with TSX enabled][2] this will trigger a general protection
fault.
This was the cause of a [very frustrating bug where LXD would segfault on
start-up][3].
[1]: https://lwn.net/Articles/534758/
[2]: https://software.intel.com/en-us/forums/intel-isa-extensions/topic/675036
[3]: https://bugzilla.opensuse.org/show_bug.cgi?id=1156336
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

vfs: vfs__delete: fix double-unlock of &root->mutex

---

src/gateway.c
src/leader.c
src/leader.h
src/replication.c
src/replication.h
test/unit/test_gateway.c

If a connection gets closed while a raft commit associated with a EXEC-SQL
protocol request is in progress, the prepared statement was not being finalized.
Later on, the gateway__close() and leader__close() APIs should be probably be
made asynhronous for cleaner logic.
Fixes #194.

Finalize pending SQL statements associated with EXEC_SQL commands

---

src/leader.c

This might be a case where we don't accurately report errors and end up with a "not an error" message on the client side.

Propagate errors originating from raft_barrier()

---

src/gateway.c

Some SQL exec requests such as BEGIN don't actually trigger any raft command, so
we need to explicitly check for leadership when starting to serve the request.

Check if the node is the leader also when serving SQL exec requests

---

src/gateway.c

This line was removed by accident.

Revert accidental code change in 191a495ff

---

src/fsm.c
src/gateway.c
src/server.c
src/vfs.c
src/vfs.h
test/lib/cluster.h
test/lib/runner.h
test/lib/vfs.h
test/unit/main.c
test/unit/test_vfs.c

This is a mechanical rename of all symbols in vfs.c to contain a `vfs` prefix for internal symbols and `Vfs` for exported ones. There is no logic change.
Since the resulting names tend to be longer, CamelCase has been used to shorten then. The same convention has been used in libraft to avoid collisions between symbols across files and allow for single-file amalgamation of the whole source.
Tests macros have also been updated to simplify the test hierarchy a bit.

Namespace symbols in vfs.c

---

src/command.c

This adds a check for the result of the parse function.
Without this check, pgno could be used while uninitialized and
compiliation with -Wmaybe-uninitialized issues a warning like so:
```
src/command.c: In function 'command_frames__page_numbers':
src/command.c:156:22: warning: 'pgno' may be used uninitialized in this function [-Wmaybe-uninitialized]
156 |   (*page_numbers)[i] = pgno;
|   ~~~~~~~~~~~~~~~~~~~^~~~~~
```

fix(command): check for uint64 parse error

---

src/vfs.c
test/unit/test_vfs.c

This is a purely refactoring branch that doesn't change behavior.
The goal is to achieve better separation between database and WAL logic in the custom VFS implementation that dqlite plugs into SQLite. Reading and writing operations are already different and this PR makes that difference more explicit, even in terms of data layout (see how `struct vfsContent` has been decomposed).
Further down the road this separation will become even more profound, since the custom VFS will interact more closely with the dqlite state machine in order to reduce the number failure-related edge cases we need to handle when Raft transactions fail to get committed.

Separate database and write-ahead-log logic in the custom VFS

---

Makefile.am
test/integration/main.c
test/integration/test_client.c
test/integration/test_membership.c
test/integration/test_server.c

This is just a cleanup branch that extends to `test_server.c` the use of slightly simpler an more flexible test macros that were introduced in earlier branches. It also moves tests that actually involve client interaction to a separate `test_client.c` file.

Use new test macros in server unit tests

---

Makefile.am
include/dqlite.h
src/dqlite.c
src/server.c
src/vfs.c
src/vfs.h
test/integration/test_vfs.c
test/lib/cluster.h
test/lib/vfs.h
test/unit/test_vfs.c

This is the initial scaffolding implementation of the new `dqlite_vfs_init()` and `dqlite_vfs_close()` public APIs, which will be used to expose the dqlite's custom version of the `sqlite3_vfs` interface. The implementation of the VFS object returned by `dqlite_vfs_init()` will differ a bit from the current one, so internally they are differentiated with the `V1` and `V2` tag.
There are no actual behavior changes for users, since the new implementation won't be really used until later on, when we'll move away from the dependency on the SQLite replication patch.
There's also a small refactoring which breaks `vfsFileShmMap()` into more granular sub-functions.

Initial public APIs exposing dqlite's custom VFS

---

Makefile.am
include/dqlite.h
src/dqlite.c
src/format.c
src/format.h
src/leader.c
src/vfs.c
src/vfs.h
test/integration/test_vfs.c
test/unit/test_format.c
test/unit/test_replication.c
test/unit/test_vfs.c

This branch adds the initial implementation of the `dqlite_vfs_poll()` and `dqlite_vfs_commit()` APIs that can be used to replicate the write-ahead log without needing to patch SQLite and introduce custom hooks.
Existing behavior for current users is unchanged, since these new APIs apply only to the "V2" version of the custom dqlite VFS, which is not used by default. Actual use of this functionality will happen later down the road when we start switching the core engine to it.

Initial implementation of VFS replication APIs

---

test/integration/test_vfs.c

==199893==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x619000004178 in thread T0
#0 0x7fd51bdab7cf in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.5+0x10d7cf)
#1 0x56243f445145 in mem_fault_free test/lib/heap.c:57
#2 0x7fd51bb8b70e in sqlite3_free sqlite3.c:28007
#3 0x7fd51bb8b70e in sqlite3_free sqlite3.c:27999
#4 0x56243f43a95e in test_vfs_pollAfterWriteTransaction test/integration/test_vfs.c:238
#5 0x56243f44a1a9 in munit_test_runner_exec test/lib/munit.c:1195
#6 0x56243f44b198 in munit_test_runner_run_test_with_params test/lib/munit.c:1357
#7 0x56243f44d81c in munit_test_runner_run_test test/lib/munit.c:1585
#8 0x56243f44e917 in munit_test_runner_run_suite test/lib/munit.c:1678
#9 0x56243f44eaf1 in munit_test_runner_run_suite …

fix: do not free munit allocations with sqlite3_free

---

test/integration/test_membership.c
test/lib/server.c
test/lib/server.h
test/unit/test_conn.c

This fixes running in tests in parallel, as reported by @mjeanson in [this comment](https://github.com/canonical/dqlite/pull/247#discussion_r464621189).

Fix flaky tests

---

include/dqlite.h
src/dqlite.c
src/format.c
src/format.h
src/vfs.c
src/vfs.h
test/integration/test_vfs.c
test/unit/test_vfs.c

The new `dqlite_vfs_abort()` API can be used to cancel pending write transactions that could not be safely replicated.
Also, the WAL header gets now generated immediately when a `PRAGMA journal=WAL` statement is issued, allowing a "follower" VFS to accept replication changes via `dqlite_vfs_commit()` even when the database is empty.
In addition to that, the `struct vfsContent` indirection between `sqlite3_file` and `struct vfsDatabase` has been removed, simplifying a bit the data layout.

Add dqlite_vfs_abort() to cancel pending transaction

---

src/vfs.c
test/unit/test_vfs.c

This had been changed to return the size of the WAL header, but it breaks
consumers.

vfs: Return 0 as size of the WAL file if there are no frames

---

src/fsm.c
src/gateway.c
src/vfs.c
test/lib/heap.c

To take raft snapshots and serve database dump requests, use the `dqlite_vfs_snapshot()` API introduced in #256, which knows more about the internal vfs data structures, instead of the older `VfsReadFile` which makes assumptions that are no longer true with the V2 vfs engine.

Use VfsSnapshot() instead of VfsFileRead()

---

src/format.c
src/format.h
src/vfs.c
test/unit/test_vfs.c

This branch contains a number of cleanups including some code and data structure simplifications, most importantly dropping the `vfsDatabase->page_size` cache and using directly the value stored in the header of the first database page. This avoids the possibility of the two values getting out of sync.

vfs: Drop unnecessary page_size cache from struct vfsDatabase

---

.travis.yml
dqlite.pc.in

Also fixes a leftover reference to `libco` in `dqlite.pc.in`.

Don't pull the libco-dev package in the Travis job

---

src/conn.c
src/fsm.c
src/gateway.c
src/leader.c
src/server.c
src/server.h
src/vfs.c

This branch contains fixes or workarounds for a few of the issues surfaced during Jepsen testing, in particular it prevents any new transaction from being started once a checkpoint is in progress and it immediately closes clients when a leader steps down.

Fixes for issues surfaced by Jepsen tests

---

test/unit/test_vfs.c

Fix 'main' is usually a function warning for tests

---

src/server.c

During testing of TLS I found that MacOS don't support abstract sockets and there is a bug I introduced in https://github.com/canonical/dqlite/pull/285 - so moved to the usual sockets for Mac and fixed checking of the client process PID.
The other patches in series:
* canonical/go-dqlite#132
* #285
* #288
* canonical/raft#173

Fixed a couple of issues with unix sockets on MacOS

---

src/gateway.c

In case RAFT uses non-async IO backend - dqlite will be unable to execute `g->req` - it will be `NULL` and cause segfault in `raftChangeCb`:`SUCCESS` callback execution.
Not sure why those lines are actually set after `raft_` func call - so moved forward and that finally allowed to work macos->macos and macos->linux nodes communication.
The other patches in series:
* canonical/go-dqlite#132
* canonical/dqlite#285
* https://github.com/canonical/dqlite/pull/290
* https://github.com/canonical/raft/pull/173

Fixed the segfault in case raft uses direct IO backend

---

src/server.c

Raft paper suggests a 1/10 ratio between HeartBeat timeout and election
timeout.
As discussed in https://github.com/canonical/raft/pull/197

server: Lower default HeartBeat timeout.

---

src/server.c

This reverts commit 7594d6d2acf7d11bb9752193842aad72890951d5.
Somehow makes the LXD cluster tests more flaky. To be investigated further.

Revert "server: Lower default HeartBeat timeout."

---

README.md

Updated README to have libsqlite3-dev as a requirement as referenced in #303

Added libsqlite3-dev to the required portion of the Build section

---

configure.ac
include/dqlite.h
src/dqlite.c

Additionally define DQLITE_VERSION_XXXXX macros to allow
feature detection.

dqlite: Bump version to 1.8.0

---

test/lib/runner.h

see https://github.com/joyent/libuv/issues/1254.
Should make the test suite more robust in case a client closes a pipe to the server.

test-runner: Ignore SIGPIPE

---

README.md

I noticed that the LICENSE-link in the README was incorrect, it caused a 404 for me. Maybe something has changes in GitHubs end, since this link it rather old.

Fix LICENSE path linked from README

---

src/gateway.c
test/unit/test_gateway.c

Fixes https://github.com/canonical/dqlite/issues/349.
After this PR, when we receive empty SQL statements, we will return a failure when a `prepare` or `query_sql` is requested.
`exec_sql` will succeed when presented with an empty SQL statement.
I could have returned success for a `prepare` request containing an empty statement, but there is no real convention what the `stmt_id` should be in that case, I thought a failure is more reasonable in this case. Same for `query_sql`, I could have returned an empty ROWS response instead of a failure.
What do you think @freeekanayaka ?

gateway: Handle empty query statements

---

src/server.c
test/integration/test_node.c

Allows to test snapshots more in jepsen tests.

server: Loosen snapshot_trailing restriction

---

Makefile.am
test/integration/test_client.c
test/integration/test_cluster.c
test/integration/test_membership.c
test/lib/client.h
test/lib/server.c
test/lib/server.h
test/unit/test_conn.c

- Move some duplicated utility macros
- Add a new test suite, `cluster` which will be used to test some end-to-end functionality. Currently have added tests to see if the database survives node restarts and if the database is transferred to new servers for different cases (with/without snapshots). 
This PR is meant to reduce the size of https://github.com/canonical/dqlite/pull/356 so it will be easier to review.

cluster tests

---

src/client.c
src/client.h
src/conn.c
src/conn.h
src/server.c
test/integration/test_fsm.c
test/integration/test_membership.c
test/lib/client.h
test/lib/server.c
test/lib/server.h

I'm trying to resolve an issue where an unfinished transaction is causing issues after a leadership transfer, the scenario is more or less as follows:
- Node 1 is leader, Node 2 is follower 
- Node 1 receives BEGIN - QUERY XXXX - ...  (notice that it doesn't receive a COMMIT message)
- Node 1 transfers leadership to Node 2, or loses leadership in some way
- Node 2 writes some data to the db
- Node 1 receives the frames, from Node 2, tries to apply them to the DB and triggers an Assert due to the pending transaction in the leader connection from step 2 that is holding locks. https://github.com/canonical/dqlite/blob/f20941be3b2a86f83ebaec1aa7dabfc4e60ac170/src/vfs.c#L2371
The `transferPendingTransaction` test tests this scenario.
This PR is just to ask for a bit of feedback on the possible …

Close leader connection

---

src/client.c
src/client.h
src/conn.c
src/conn.h
src/server.c
test/integration/test_fsm.c
test/integration/test_membership.c
test/lib/client.h
test/lib/server.c
test/lib/server.h

Reverts canonical/dqlite#354
The LXD proxy is not liking the fact that I close the network connections, already have a fix for this, will revert for now.

Revert "Close leader connection"

---

src/client.c
src/client.h
src/gateway.c
src/gateway.h
src/lib/registry.h
src/server.c
test/integration/test_fsm.c
test/integration/test_membership.c
test/lib/client.h
test/lib/server.c
test/lib/server.h

As discussed in https://github.com/canonical/go-dqlite/pull/186, similar to https://github.com/canonical/dqlite/pull/354, but instead of closing the network connection, it only closes the `gateway->leader` and the SQLite connection it contains. Only the last commit contains unreviewed changes.
Ongoing requests will be canceled with `LEADERSHIP_LOST`, future requests will err out with `SQLITE_NOTFOUND` because the database is not opened. This should be viewed in conjunction with https://github.com/canonical/go-dqlite/pull/187 that will mark the connection as bad resulting in the driver to reopen a new connection.
`LOOKUP_DB` at the start of the gateway functions that deal with the SQLite leader connection will err out with `SQLITE_NOTFOUND` after the node has lost leadership, so a leader …

Close leader sql connection

---

src/leader.c
src/leader.h

This field was necessary only in the old implementation that used coroutines and
the patched SQLite version. It can be dropped now.

Remove the legacy "done" field from struct exec

---

src/server.c

This fixes a couple of cases where a function belonging to the dqlite public API could return with a non-dqlite error code. See #379 -- I've left src/vfs.c alone for now because I'm not sure whether the functions in src/vfs.h should be using dqlite return codes or sqlite codes, but I can add a commit addressing those functions once the convention is established.

Fix non-dqlite return codes in public API

---

README.md

I mixed up Linux's native async I/O facilities with POSIX AIO -- raft uses the first one.

README: fix statement about AIO

---

include/dqlite.h
src/server.c
src/server.h

This implements roughly @freeekanayaka's suggestion in https://github.com/canonical/raft/issues/228. If we agree this is the way to go, I'll make a PR to go-dqlite to adjust its behavior accordingly.
Note that unlike Free's sample code in that thread, I don't differentiate in the public API between DQLITE_NOMEM errors and other kinds of errors. Instead, dqlite_node_errmsg and dqlite_node_destroy just handle NULL arguments gracefully. I went this route because it makes callers' lives simpler and because DQLITE_NOMEM is an ambiguous signal -- was it the `struct dqlite_node` allocation that failed, or some other allocation along the way?

Expose string errors from dqlite_node_create

---

Makefile.am
src/client.c
src/lib/byte.h
src/lib/serialize.h
src/transport.c
src/tuple.c
src/vfs.c
test/unit/lib/test_byte.c
test/unit/lib/test_serialize.c
test/unit/test_tuple.c

Also rename functions from that header in camel-case style.
Closes #385.

Move endian-sensitive code to src/lib/byte.h

---

Makefile.am
configure.ac
src/lib/byte.h
src/logger.c
test/lib/logger.c

Should fix the Launchpad build failures we saw. I'm not sure why -Wconversion didn't fire in our GHA CI -- different compiler versions, maybe?

lib/byte: Rewrite to avoid triggering -Wconversion

---

Makefile.am

Since we already ignore -Wmaybe-uninitialized. This is more fallout from enabling -Werror in #387. Should fix the latest Launchpad build failures (I wish I knew why GHA didn't catch this one).

Also ignore -Wuninitialized for tests

---

src/lib/buffer.c

This should address some defects that were reported in the most recent Coverity run.
I don't have a strong sense of what `MAX_REASONABLE_SIZE` should be (hence the `// XXX`) -- suggestions welcome.

lib/buffer: Sanity-check argument of buffer__advance

---

src/lib/buffer.c

@MathieuBordere pointed out that we do want to buffer__advance by more than 1 GiB in some cases, so this fix would break valid applications. I'll follow up with a more targeted fix for the Coverity defects.

Revert "lib/buffer: Sanity-check argument of buffer__advance"

---

src/lib/buffer.c

Small optimization in order not to `realloc` the data buffer multiple times in the loop.

buffer: Don't unnecessarily realloc in loop.

---

test/lib/runner.h

dqliteTracingMaybeEnable is called when we stand up a server, but that doesn't help for most of the unit tests, which call various internal bits of dqlite directly. So, add a separate call to dqliteTracingMaybeEnable in the generated main function for our test suites.

test: Make sure tracing is enabled

---

src/lib/util.h
src/tracing.h
src/utils.h

Often find myself using this macro to debug.
I also moved the contents from lib/util.h to utils.h, I didn't notice there was a `utils` header when I introduced the likely macro's.

utils: Define DBG macro

---

src/vfs.c
test/integration/test_vfs.c
test/unit/test_vfs.c

Avoids memory corruption uncovered by the added tests.

vfs fnctl fix

---

Makefile.am
src/client.c
src/conn.c
src/gateway.c
src/gateway.h
test/integration/test_membership.c
test/lib/raft_heap.c
test/lib/raft_heap.h
test/unit/test_concurrency.c
test/unit/test_gateway.c

WIP, tests will need fixing. See https://github.com/canonical/raft/issues/302.
Closes #210
Closes https://github.com/canonical/go-dqlite/issues/78

Add barriers before calling sqlite3_prepare_v2

---

src/gateway.c
test/unit/test_gateway.c

This PR updates gateway.c to return a failure response in some cases when it sees a value for a version/type field that it doesn't recognize. The fields currently addressed are the request type (see [here](https://github.com/canonical/dqlite/issues/377#issuecomment-1255176012)) and the "format" field of the cluster request (see [here](https://github.com/canonical/dqlite/issues/400#issuecomment-1249472387)). I'd love to address this TODO as well:
https://github.com/canonical/dqlite/blob/607de645ca4ae282ac9267e220f91b6afc56e0f7/src/conn.c#L240-L247
But changing the handshake like that is a bigger deal and requires coordinating with go-dqlite, so I've left it alone for now.

Handle unrecognized values for a couple of fields

---

bt/request
resources/stdbool.h

This adds a single, simple script that can be used to run bpftrace against a dqlite app and record a histogram of the time spent by each raft request between enqueueing and dequeueing. Example usage:
```sh
$ make integration-test
$ sudo bt/request -I ../raft/include -c ./integration-test
```
Notes:
- Ubuntu Jammy currently packages bpftrace 0.14.0, which is unable to find some system headers on its own (this is fixed in 0.15.0); so you may have to add `-I /usr/include/x86_64-linux-gnu` to that invocation
- bpftrace knows about some libc headers, but not yet stdbool.h, so we vendor that ourselves for the moment
- raft and dqlite need to be built with debug info (`--enable-debug`)
- The environment variable `LIBRAFT_SO_PATH` is supported to point bpftrace in the right direction in case …

Proof-of-concept for instrumentation with bpftrace

---

.github/workflows/build-and-test.yml
.github/workflows/coverity.yml

- Update checkout action to v3. Fixes a Github warning for using Node 12.
- Add ubuntu 22.04 to test matrix. Github is phasing out support for ubuntu 18.04 in april 2023 https://github.com/actions/runner-images/issues/6002 Tests on 18.04 will fail during the "brown-out" periods until then. Add ubuntu 22.04 to test suite to prep for removal of 18.04.

.github: update actions

---

src/gateway.c
src/leader.c
test/integration/test_membership.c
test/lib/util.h

Fixes #416.
The test hits the same segfault as in the issue, the `leader->exec` was not cleaned up in case `leader__barrier` failed leading to inconsistent state.

Issue 416/null deref

---

test/unit/test_gateway.c

Fixes a test failure on ppc64le.
This fix makes sure enough rows are inserted to trigger a multi response result.

test_gateway: Insert enough rows to trigger a ROWS_PART response

---

Dockerfile

Trying to build using the Dockerfile lead to an error as liblz4 was not installed.
Unfortunately something else is also borked as it now stops when compiling dqlite:
```s
[..]
Step 13/22 : WORKDIR /opt/dqlite
---> Running in 5777fd6ffc1b
Removing intermediate container 5777fd6ffc1b
---> 3e24e33ab8a9
Step 14/22 : COPY . .
---> c86f93df29cf
Step 15/22 : RUN autoreconf -i && ./configure && make && make install
---> Running in f71c6f639f7d
autoreconf: error: 'configure.ac' is required
The command '/bin/sh -c autoreconf -i && ./configure && make && make install' returned a non-zero code: 1
```
I didnt have time so far to look into the issue.

Add missing install of dependency liblz4

---

src/fsm.c
test/integration/test_fsm.c

We were ignoring all `apply_xxx` return values except in the `switch` `default:` branch.

fsm: Don't ignore return value in fsm__apply.

---

Makefile.am
include/dqlite.h
src/config.c
src/config.h
src/db.c
src/db.h
src/dqlite.c
src/fsm.c
src/fsm.h
src/leader.c
src/lib/fs.c
src/lib/fs.h
src/server.c
src/vfs.c
src/vfs.h
test/integration/test_client.c
test/integration/test_cluster.c
test/integration/test_fsm.c
test/integration/test_membership.c
test/integration/test_node.c
test/integration/test_vfs.c
test/lib/cluster.h
test/lib/config.h
test/lib/fs.c
test/lib/server.c
test/lib/sqlite.c
test/unit/test_vfs.c

~WIP - don't review~
- Have tried to run all existing tests with the new disk vfs. Most failures come from the fsm snapshot functionality not being in place for the on-disk case.
- Not yet 100% sure about the abstraction, I feel like a user should be able to choose the VFS per database, but currently I just put the whole of dqlite in disk-mode, i.e. every database will be stored on disk. If the snapshotting behaviour is different for in-memory/on-disk, different VFS's for different databases could lead to complex snapshotting behaviour in raft, where we have to mix different methods to snapshot. Would like to avoid that.
- SYNCs are still turned off, the real transaction is the raft log being stored to disk, the database writes to disk from SQLite don't have to be synced I think.
- Still …

Initial disk mode support

---

src/fsm.c
src/vfs.c

Begins to fix some issues (#418) that limit the maximum database size to 4GB and some other things I encountered when fixing that.
- The main fix is not longer downcasting a `sqlite_int64` offset to a (most of the time) 32-bit `unsigned`. 
- Added some explicit casts when operating on values of different signedness.
- Cast `void*` to `char*` before doing pointer arithmetic.

Issue 418/db size

---

src/db.c
src/leader.c
test/unit/test_gateway.c

leader, db: Prevent client from attaching more DBs

---

Makefile.am
configure.ac
src/lib/assert.h

Support printing backtrace when an assertion fails

---

src/gateway.c
src/gateway.h

This PR refactors gateway.c to store several pieces of request-scoped data in the request handle object instead of the gateway itself. In the process, I fixed (?) how we handle parameters to multi-statement EXEC_SQL requests.

Refactor gateway.c

---

src/gateway.c

The statement lookup in leader_exec_cb is infallible, because we've already looked up the same stmt_id in order to sqlite3_step the registered statement.

gateway: Appease Coverity

---

src/gateway.c
test/integration/test_cluster.c

Closes #471. This is based on #476, I'll rebase onto master once that merges.
As suggested by @freeekanayaka, we don't support modifying statements that also return rows (for now). Modifying statements submitted with QUERY or QUERY_SQL go through exactly the same codepath as if submitted with EXEC or EXEC_SQL, respectively, except that we send an empty ROWS response instead of a RESULT response.

Support QUERY and QUERY_SQL that modify the database

---

src/conn.c
src/gateway.c
test/unit/test_gateway.c

The behavior of an interrupt request was recently changed, previously handling an interrupt when no request was active was basically a no-op, it was changed to a hard error [here](https://github.com/canonical/dqlite/commit/83c693e3754ccd9c1814ef652cf2e019a43622cd).
This breaks the package builds of `go-dqlite` on focal with `go 1.13.8`, however it doesn't seem to be caught in the go-dqlite CI tests on focal running `go 1.13.15`.
Decided to revert to previous behavior, unless there's a good reason to change it.
edit: Added a - currently failing - test that actually interrupts a `query_sql` instead of `query`. Apparently there's also an issue with the cleanup code that broke around the same time the other behavior broke.
edit2: So if a request comes in on the same connection, `req` and …

gateway: accept interrupt when no query active

---

test/lib/munit.c

Came up while looking into #488.

munit.c: Fix compilation with -DMUNIT_NO_BUFFER

---

src/conn.c

This is a trivial change that makes it possible to build a dqlite.c amalgamation -- without it there's a name clash with the write_cb in src/lib/transport.c.

conn: Rename write_cb

---

src/format.c
src/vfs.c
test/unit/test_tuple.c

I've been messing around with using Fabrice Bellard's tcc for local builds; this is the only change that's really required for libdqlite to build successfully (have not tried the test suite yet).
The only reason we call __builtin_assume_aligned is to silence a warning from GCC/Clang about unaligned accesses; tcc doesn't have that warning.

Polyfill __builtin_assume_aligned for tcc

---

src/vfs.c

Before this change, a call to vfsDatabaseLookup with filename "blah" could end up opening a database named "blahblah" (n = strlen("blah") = 4, strncmp("blah", "blahblah", 4) = 0).

vfs: Fix buggy database filename comparison

---

src/client/protocol.c
src/client/protocol.h
test/integration/test_fsm.c

This matches how other functions in client/protocol.c work and is less error-prone.

client/protocol: Return owned error message from clientRecvFailure

---

.github/dependabot.yml

- dependabot periodically checks for outdated dependencies and raises PRs to update if there are any
- maintained and supported by GitHub
- configured in a `dependabot.yml` file 
- having the `dependabot.yml` file automatically activates dependabot
- further options can be found under _Settings_ -> _Code security and analysis_ -> _Dependabot_
- more information [here](https://docs.github.com/en/code-security/dependabot)
- adds the `dependabot.yml` file to the `.github` folder
- the added `dependabot.yml` is already configured to check all _github-actions_ once every week for dependencies updates

Add dependabot to manage dependencies updates of github-actions

---

Makefile.am
src/bind.c
src/bind.h
src/conn.c
src/conn.h
src/gateway.c
src/gateway.h
src/revamp.c
src/revamp.h
src/server.c
src/server.h
src/tuple.h

This is the first chunk of work on the new design for data storage/VFS on the dqlite side. It's exclusively scaffolding to set up the new DB thread and prepare to pass things to it.
The next step is to work out how clients on the main thread will cause databases to be opened on the main thread -- we can probably re-use the DB registry code here. Likewise for preparing statements. This will involve writing a proper main loop for the DB thread. (I think it makes sense to keep the "old way" code around, working in parallel, while the "new way" code is being developed.) After that the main thread should be able to pass (parsed versions of) client requests to the DB thread -- maybe just EXEC or EXEC_SQL to start, if that's easier. That will set things up to start working on the new VFS. …

Start of work on dqlite revamp

---

src/revamp.c
src/revamp.h
src/server.c

Next steps:
- There is a deadlock in the new mutex/condvar interaction that needs fixing.
- Sending the EXEC_SQL request to the DB thread at the appropriate place in gateway.c, and waiting for the DB thread to respond before the end of the request's lifecycle (by receiving an acknowledgement on another queue/channel). The DB thread doesn't have to do anything with the request yet.
- Having the DB thread open databases in response to the received requests, prepare statements, and execute them, using the normal VFS for now. (We should probably make up a subdirectory of the data directory for those files to live in.)

More revamp work: preparing to send requests to the DB thread

---

.github/workflows/packages.yml

Add mantic packages.
Best to wait for raft packages to be published before starting to build dqlite ppa packages.

packages: Add mantic.

---

Makefile.am
configure.ac

See [here](https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html#Options-for-Debugging-Your-Program) for the description of what `-g3` does. More debuginfo seems better to me!

Include more debug info in debug builds

---

src/vfs.c

See here: https://github.com/sqlite/sqlite/blob/2aae3a95a97e38d82ec89d8b63ff5a9255b12225/src/btree.c#L5139-L5168

vfs: Weaken assertion to accomodate SQLITE_DIRECT_OVERFLOW_READ

---

src/conn.c
src/conn.h
src/gateway.c
src/lib/transport.c
src/lib/transport.h
test/integration/test_client.c
test/lib/client.h
test/unit/lib/test_transport.c

Allow to interrupt a query yielding rows, whereas in the past the interrupt request was only handled - after - all rows were returned.
To make this work I had to allow multiple pending writes to the transport because the query that's yielding rows is writing to the transport, but when an interrupt comes in, we also want the interrupt handler to be able to write to the transport. As long as messages are written as whole and `uv_write_t` doesn't interleave data of 2 writes [1] then this should be okay.
DRAFT: running tests and upstream tests and also want to check if I'm violating some assumptions by allowing multiple writes, basically checking [1].
EDIT: writes with `uv_write_t` are queued and execute in order, so multiple writes should be fine. dqlite also sends data with message …

Interrupt query yielding rows.

---

src/conn.c
src/conn.h
src/gateway.c
src/lib/transport.c
src/lib/transport.h
test/integration/test_client.c
test/lib/client.h
test/unit/lib/test_transport.c

This reverts commit 4ca4dae94ce7e7002a1142020cfafd09caa0fdb5, reversing changes made to 71562ee9897634606ac5a21921dc368aac97cb91.
Fix was buggy, needs a more thorough refactoring of request handling on a connection.

Revert "Merge pull request #560 from MathieuBordere/interrupt"

---

src/client/protocol.c
src/command.c
src/conn.c
src/fsm.c
src/gateway.c
src/lib/serialize.h
src/query.c
src/transport.c
src/tuple.c
test/unit/lib/test_serialize.c
test/unit/test_concurrency.c
test/unit/test_gateway.c
test/unit/test_request.c
test/unit/test_tuple.c

Currently we use `void *` as a cursor type when parsing and serializing, and this results in many cases of performing arithmetic on void pointers -- technically UB. Change these types to `char *` everywhere.

Fix many cases of arithmetic on void pointers

---

src/lib/threadpool.c

Pointed out by GCC on one of the LP builders.

Fix use-after-free in threadpool code

---

src/raft/uv_fs.c

The file descriptor leak here was noted by the LXD folks: https://github.com/canonical/lxd/issues/12808#issuecomment-1969219953
cc @tomponline @simondeziel

raft: Close fd used for fallocate probing

---

.github/workflows/coverity.yml

Use --enable-build-raft for Coverity

---

.gitignore
test/unit/test_conn.c

On armhf casting to uint64_t* produces the following warning
"cast increases required alignment of target type". Remove
the hack of saving a pointer to bool in a field that's not
meant to hold it.
Fixes launchpad builds.

test_conn: Fix changed alignment requirements.

---

src/raft/uv_ip.c
src/raft/uv_tcp_connect.c

This is cherry-picked from https://github.com/cowsql/raft/commit/1a00ebf0482000d8b62ea1932bb88122a951aaba -- thanks @freeekanayaka for pointing out the fix.
Closes #574

raft/uv: Drop AI_V4MAPPED | AI_ADDRCONFIG from getaddrinfo

---

src/client/protocol.c

Fixes this Launchpad build failure on armhf: https://launchpad.net/~dqlite/+archive/ubuntu/dev/+build/27853399
```console
src/client/protocol.c: In function ‘doRead’:
src/client/protocol.c:143:29: error: conversion from ‘__time64_t’ {aka ‘long long int’} to ‘long int’ may change value [-Werror=conversion]
143 |                             (context->deadline.tv_sec - now.tv_sec) * 1000 +
|                             ^
src/client/protocol.c: In function ‘doWrite’:
src/client/protocol.c:223:29: error: conversion from ‘__time64_t’ {aka ‘long long int’} to ‘long int’ may change value [-Werror=conversion]
223 |                             (context->deadline.tv_sec - now.tv_sec) * 1000 +
|                             ^
```
(I don't know why these warnings didn't fire before -- either a GCC …

client/protocol: Ensure 64 bits for nanosecond calculations

---

src/lib/sm.c

This makes the traces easier to read.

sm: Trace states by name

---

src/lib/byte.h
src/lib/sm.c
src/lib/sm.h
src/utils.h
src/vfs2.c
src/vfs2.h
test/lib/runner.h
test/unit/test_vfs2.c

The headline change is that almost everything now lives in the linked-list entry, but various other changes were swept up in this as well.
Still incomplete, the state machine needs to be updated along with the implementations of the vfs2.h functions and quite a few smaller TODOs that I've tried to note in the code for my own benefit.
The big refactor was motivated by thinking in more detail about how the WAL-index is going to be managed throughout the node's whole lifetime, including the "follower" part that I'd previously neglected. I think I now have a good mental model for this, which I intend to write down as a doc comment on the state machine stuff once that is brought up to date/stabilized.

Refactor vfs2

---

src/raft/uv_fs.c
src/raft/uv_os.c
src/tracing.c

This unbreaks the dqlite build on alpha and x32. Supersedes #634; thanks @gibmat for the patch.

Three portability fixes around integer width

---

test/unit/test_vfs2.c

These cause the LP builds to fail on armhf due to the usual integer width headaches, and probably shouldn't have been committed in the first place.

Remove two tracing lines from vfs2 test

---

.github/workflows/build-and-test.yml

github: Test on Ubuntu Noble

---

.github/workflows/latest-deps.yml
Makefile.am

Add CI job for latest SQLite, libuv, liblz4

---

src/raft/uv_writer.c

@marco6 pointed out this `return` that should be a `continue`, which causes us to skip processing some KAIO write results if we get several of them in a batch and one of them has status code EAGAIN.
In practice, when running our test suite, it seems that io_getevents never returns more than one event in this context, which together with the dependence on getting EAGAIN explains why we never noticed this while developing dqlite or raft. But in production we could certainly encounter `n_events > 1`.

uv_writer: Don't skip later KAIO events when one is EAGAIN

---

src/config.c
src/config.h
src/db.c
src/server.c
src/server.h
test/integration/test_node.c
test/lib/cluster.h
test/lib/config.h

It was suggested that some of the corruption issues reported by LXD users might be due to two LXD daemon processes running concurrently, causing two dqlite instances to concurrently modify the common data directory. LXD already has some mutual exclusion logic to prevent two daemons from running at the same time:
https://github.com/canonical/lxd/blob/1514a400f11a82b90a5294b5c1f31cd2c6dd9311/lxd/endpoints/socket.go#L39
But even so it seems worth it to do some file locking to prevent this definitively on the dqlite side.
Note that this obviously won't work unless both the contending processes are running versions of dqlite that include the locking.

Add file locking to prevent two dqlite instances from using the same directory concurrently

---

Makefile.am
src/lib/sm.c
src/lib/sm.h
src/lib/threadpool.c
src/raft/recv_install_snapshot.c
src/vfs2.c
test/raft/lib/runner.h
test/raft/unit/test_snapshot.c
test/unit/test_sm.c

This is the `chronoscope.yaml` used:
```
.p1: &tick_parser_positions
id: 10
pid: 8
type: 6
time: 1
event: 11
.p2: &rel_parser_positions
type: 6
orig_pid: 8
dest_pid: 10
orig_id: 12
dest_id: 14
.p3: &attr_parser_positions
id: 6
pid: 4
type: 2
name: 7
value: 1
tick:
- type: follower
pos: *tick_parser_positions
- type: leader
pos: *tick_parser_positions
- type: work
pos: *tick_parser_positions
- type: rpc
pos: *tick_parser_positions
- type: to
pos: *tick_parser_positions
relation:
- type: leader-to-rpc
pos: *rel_parser_positions
- type: leader-to-work
pos: *rel_parser_positions
- type: leader-to-to
pos: *rel_parser_positions
- type: follower-to-rpc
pos: *rel_parser_positions
- type: follower-to-work
pos: *rel_parser_positions
- type: follower-to-to
pos: *rel_parser_positions
attr:
- type: …
```

feat: integrate anatoliy o11y prototype

---

src/lib/sm.c

Addresses this LP build failure from the LXD builder: https://launchpadlibrarian.net/738518550/buildlog_snap_ubuntu_jammy_armhf_lxd-5.21-edge_BUILDING.txt.gz

sm: Fix format specifiers for armhf

---

src/raft/uv_list.c

Got a UAF on an old version of Dqlite. This should fix it.
```
==2760859==ERROR: AddressSanitizer: heap-use-after-free on address 0x613000020140 at pc 0x7f3514979bbc bp 0x7f34c73cc720 sp 0x7f34c73cc710
READ of size 1 at 0x613000020140 thread T8
#0 0x7f3514979bbb  (/usr/local/lib/libraft.so.2+0x67bbb)     /home/zyh/raft/src/uv_segment.c:91
#1 0x7f351466d780  (/lib/x86_64-linux-gnu/libc.so.6+0x45780)
#2 0x7f351466d6a1  (/lib/x86_64-linux-gnu/libc.so.6+0x456a1)
#3 0x7f351466d684  (/lib/x86_64-linux-gnu/libc.so.6+0x45684)
#4 0x7f351466dc9d  (/lib/x86_64-linux-gnu/libc.so.6+0x45c9d)
#5 0x7f3514972bb4  (/usr/local/lib/libraft.so.2+0x60bb4)              /home/zyh/raft/src/uv_list.c:112
#6 0x7f351498a283  (/usr/local/lib/libraft.so.2+0x78283)              /home/zyh/raft/src/uv_snapshot.c:715
#7 …
```

Fix a possible UAF

---

src/raft/recv_install_snapshot.c
src/raft/recv_install_snapshot.h
test/raft/unit/test_snapshot.c

Added both unit tests and tests that use libuv timers directly

feat: proper timeout handling for snapshots

---

src/gateway.c
test/unit/test_gateway.c

After preparing more queries on k8s-dqlite, I've been hitting quite frequently some segfaults. They all seemed to be happening when a query is running and the node is shutting down.
Apparently, they were. There was some missing cleanup logic around prepared statements in `gateway__leader_close`. This PR adds that bit.
I see that codecov report is showing a small regression in coverage. If someone from the dqlite team could guide me in testing this, I would be up for it.

Cleanup prepared statement during node close

---

Makefile.am
src/lib/threadpool.c
src/lib/threadpool.h
src/raft.h
src/raft/recv_install_snapshot.c
src/raft/recv_install_snapshot.h
test/raft/unit/test_snapshot.c

This PR integrates the pool with the snapshot installation. This is a first version without the real implementation for the callbacks and I/O. It solves a few issues found along the way, namely it includes:
* pool integration for background work,
* emulating the async nature of rpc sending by scheduling a callback using libuv,
* first versions of rpc_fill and is_a_trigger, that means that the code can now generate primitive messages and expect the correct ones,
* tests now assert that the messages sent are the correct ones,
* added missing state which I noticed when writing new tests.
See the commit list for more information as the functionality is split into self-contained units.

Snapshot pool integration, first version

---

src/conn.c
src/gateway.c
src/gateway.h
src/leader.c
src/leader.h
test/integration/test_client.c
test/unit/test_concurrency.c
test/unit/test_gateway.c

#679 turned up the fact that we can enter bounded recursion in `handle_exec_sql`, with the maximum number of stack frames being proportional to the number of `;`-separated statements in the `EXEC_SQL` request. This PR breaks that recursion by yielding to the event loop at one link in the chain.

gateway: Break recursion in handle_exec_sql

---

src/conn.c
src/gateway.c
src/gateway.h
src/leader.c
src/leader.h
test/integration/test_client.c
test/unit/test_concurrency.c
test/unit/test_gateway.c

This reverts #681 in response to the regression #684.

Revert suspending inside handle_exec_sql

---

src/gateway.c
src/lib/threadpool.c
src/lib/threadpool.h
test/raft/unit/test_snapshot.c
test/unit/test_conn.c

Free the pool's `pool_impl_t` containing the `outq_async` handle only after the callback passed to `uv_close` has fired, in line with [libuv rules](https://docs.libuv.org/en/v1.x/handle.html#c.uv_close), and in contrast to the original code, which could free this allocation while libuv was still holding a pointer into it. This UAF showed up in CI runs for #682 but is hard to reproduce otherwise.
Note that dqlite as used in production is not affected by this bug since the thread pool is not even created in that case.

Fix use-after-free in unit tests

---

src/conn.c
src/conn.h
src/gateway.c
src/gateway.h
src/leader.c
src/leader.h
test/integration/test_client.c
test/unit/test_concurrency.c
test/unit/test_gateway.c

Revised version of the reverted #681, fixing the regression #684. The bug in that PR was of the same type as that fixed in #686: passing a `NULL` callback when `uv_close`-ing a handle and then freeing the allocation containing the handle immediately.
To fix this instance of the bug, I put the `uv_timer_t` in the `conn` object instead of the gateway, since `conn` already has an asynchronous closing sequence. This means the gateway goes back to not knowing that it's running on an event loop, which is convenient for the tests.
It's probably most efficient to review this by looking at the diff against the previous PR, as merged:
```console
$ git remote add cole https://github.com/cole-miller/dqlite
$ git fetch cole
$ git diff 7dea935c44a32d1a4006ae23e072aef6f9cce509 cole/exec-sql-suspend-v2 …
```

Break recursion in handle_exec_sql_next (second attempt)

---

include/dqlite.h
src/raft.h
src/raft/raft.c
src/server.c
test/integration/test_cluster.c
test/lib/client.h
test/lib/server.c
test/lib/server.h

This enables better automation of dqlite_node_recover_ext by exposing enough information to determine which of several nodes has the most up-to-date log. See https://github.com/canonical/go-dqlite/issues/299. Exposing this from libdqlite is the first step, then we can add a wrapper API in go-dqlite.
The implementation in this PR is as simple as calling the `load` method of the uv raft_io object. This is wasteful---it loads all snapshots and entries into memory---but that seems acceptable to me, since it's no more expensive than restarting the node normally and the use-case is an exceptional failure condition (loss of quorum).

Add an API for querying the last raft log entry

---

.github/workflows/build-and-test.yml
test/unit/lib/test_registry.c
test/unit/test_vfs2.c

We know which binary is hanging now, try to get some backtraces using GDB if it looks like it's hanging.

Grab stack traces when unit test hangs

---

.github/workflows/nolz4.yaml
configure.ac

The build was broken when `--enable-build-raft` was passed and liblz4 was missing due to a logic error in configure.ac. Fix this and test this particular build configuration in CI.
I only noticed this because we don't install liblz4-dev for the PPA builds and it's preventing setting `--enable-build-raft` there (canonical/dqlite-ppa#7).

Fix the build when liblz4 is missing and test it

---

configure.ac
src/lib/sm.c
src/lib/sm.h
src/logger.c
test/lib/logger.c

Small fixes and one addition for sm.c, pulled from #678 to make review easier.

Fixes for sm.c

---

src/raft/raft.c
src/raft/uv.c
src/server.c

At the moment, the raft_recover error messages are not propagated, so the caller gets a cryptic error code (1), without further details.
This change ensures that the error messages are propagated and adds a few extra trace messages.
Furthermore, tracing is disabled unless we start the node (not the case when we're actually trying to recover it). For now, we're adding a "dqliteTracingMaybeEnable" call in "dqlite_node_recover_ext".

Propagate raft_recover errors and improve tracing

---

src/leader.c

VfsPoll can fail to acquire the WAL write lock, and the caller still needs to release the frames of the transaction in this case. Restores the behavior from before the exec_tick rewrite. Hat tip @marco6.

Fix frames leak when VfsPoll fails

---

.github/workflows/packages.yml

Something weird happened the first time and the `dqlite1.17` packages that got published to the PPA come from the wrong commit.

Trivial change to force package rebuild

---

src/raft/replication.c

It's not expected that the reference to the `entry` is taken in all places in the code. That's why every time it's accessed without taking a reference it's needed to save term and index of the `entry` to access it later through `log_get_entry_sm()`.

In replication scenario, entry_sm gets updated every time it is used.

---

src/bind.c
src/lib/serialize.h
src/query.c
src/tuple.c
src/tuple.h
test/unit/test_tuple.c

This PR renames the `float_t` type to `real_t` so that it doesn't clash with `float_t` defined in `math.h`.
While the build issue is caused by libuv now importing `math.h` in their header (?!) this was a mistake since the start: a program that redefines a standard type is ill-formed.
I chose `real_t` to match SQL types listed in the SQLite manual at https://www.sqlite.org/datatype3.html

chore: rename float_t to real_t

---

.github/workflows/build-and-test.yml

Given that Ubuntu Focal Fossa (20.04) is EOL and jobs cannot run anymore this PR removes support for it in v1.18.
v1.17 can still support that version.

chore: drop support for 20.04

---

src/tracing.c
src/tracing.h
src/utils.h

This PR wraps the logic to write traces in a noinline function so that stack message will not take space in the stack frame of the caller.
Related: #679. I'm really not sure if it is enough to fix it though.

fix: reduce trace stack usage

---

src/fsm.c
src/raft/snapshot.c
src/vfs.c

This PR changes a bit the logic to free snapshot headers as the stress test in #740 showed a bug: while it is true that pages are never freed and can be shallowly referenced, the size of the database might change as writes are still allowed to continue during snapshot. This results in freeing the wrong buffer as the size of the database is used to "skip" buffers during finalize time.
The solution here uses the information stored *in the header* for each database instead.

fix: free shallow snapshot headers correctly

---

Makefile.am
src/raft.h
src/raft/fixture.c
src/raft/raft.c
src/raft/recv_install_snapshot.c
src/raft/uv.c
src/raft/uv.h
src/raft/uv_timer.c
src/raft/uv_writer.c
src/utils.h
test/raft/integration/test_snapshot.c
test/raft/integration/test_uv_timer.c
test/raft/lib/loop.c

This PR adds the ability to start/stop timers on the `raft_io` object.
This was a part of #740 and is an effort to reduce its size.

feat: add timers support in raft_io

---

src/bind.c

The whole protocol and the `gateway.c` implementation assume that the current request message is fixed in memory and is never overwritten until a response has been sent (including multiple message responses like the query rows). This is also why the part around interrupting long queries doesn't work.
Given that the solution to the above would be to allocate a message for each request, it is safe to use `SQLITE_STATIC` and let SQLite reference data in the message.

feat: use SQLITE_STATIC binding

---

src/gateway.c
src/leader.c

This PR fixes a use-after-free on the `{exec, query}_done` callback.
The problem was that if the callback of an exec or query (the one with perpared statements) calls `gateway__close` then it creates a use-after-free.
The complete picture is the following:
```C
static void handle_exec_done_cb(struct exec *exec)
{
...
sqlite3_stmt *stmt = exec->stmt;
...
if (raft_status != 0) {
exec_failure(g, req, raft_status); /* will call req->cb which is `gateway_handle_cb` */
goto done;
}
```
Which in the case of `LEADERSHIP_LOST` or `NOT_LEADER` will:
```c
static void gateway_handle_cb(struct handle *req,
int status,
uint8_t type,
uint8_t schema)
{
...
if (status == SQLITE_IOERR_NOT_LEADER || status == SQLITE_IOERR_LEADERSHIP_LOST) {
tracef("gateway handle cb status %d", status);
goto abort;
}
... …
```

fix: use-after-free for prepared statement

---

src/raft/client.c
src/raft/configuration.c
src/raft/convert.c
src/raft/election.c
src/raft/progress.c
src/raft/recv.c
src/raft/recv_append_entries.c
src/raft/recv_append_entries_result.c
src/raft/recv_install_snapshot.c
src/raft/recv_request_vote.c
src/raft/recv_request_vote_result.c
src/raft/recv_timeout_now.c
src/raft/replication.c
src/raft/snapshot.c
src/raft/start.c
src/raft/tick.c
src/raft/uv.c
src/raft/uv_finalize.c
src/raft/uv_list.c
src/raft/uv_prepare.c
src/raft/uv_recv.c
src/raft/uv_segment.c
src/raft/uv_send.c
src/raft/uv_snapshot.c
src/raft/uv_truncate.c
src/raft/uv_work.c

This PR removes a useless `#undef` at the end of every raft `.c` file.

refactor: remove useless undef

---

src/vfs.c
test/unit/test_gateway.c

This PR fixes the reading of the main file in the case of an "over the limit" read, which might happen when enabling autovacuum.

fix: read main file when out of range

---

src/raft.h
src/raft/fixture.c
test/unit/test_concurrency.c
test/unit/test_gateway.c

This PR fixes a bunch of tests in the gateway suite so that they always wait (where appropriate) and do not rely on some async operation to end synchronously.
It also adds the capability to change the expected async work duration so that it is possible to rely on that timing during test time.

test: fix wait times for gateway tests

---

src/db.c
test/unit/test_gateway.c

Following the report from LXD, this PR re-enables foreign key support by default.
It also adds a test as clearly that was a hidden promise our interface did which wasn't tested.

fix: enable foreign key support by default

---

.github/workflows/packages.yml

This PR tries to fix the PPA publishing pipeline *for the LTS 1.17.x* by running the job on a container.

chore: fix pipeline

---

src/gateway.c
test/unit/test_gateway.c

This PR fixes a misbehaviour for the `RETURNING` keyword: once the first row is returned, the query is not rolled back unless the transaction which is part of is.
This means that aborting a statement with `RETURNING` will not rollback the rows. This is expected behaviour in SQLite and should really be reflected in dqlite.
This also fixes a problem where a connection, once interrupted, could not execute any other statement. Consider though that interrupt is not supported right now, so it is not a bug that can be hit by normal code (i.e. using the `go-dqlite` package).

fix: `RETURNING` semantics

---

src/vfs.c
test/integration/test_stress.c
test/lib/client.h

This PR fixes the build on 20.04 (older GCC version) and for tests on 32-bit architectures like `armhf`.

fix: minor build issues

---

src/leader.c
test/unit/test_replication.c

This PR removes the code that coordinates checkpoint which has been a no-op since `v1.10.0`.

chore: remove support for pre-lts coordinated checkpoint

---

.github/workflows/packages.yml

This PR makes sure the PPA packages publishing workflow only runs if a version is published, so that stable version packages are not overwritten by interim packages.

chore: release on PPA only when a version is published

---

src/leader.c
test/unit/test_gateway.c

This PR fixes the leader state machine so that it always call `VfsAbort` in case something went wrong during replication. 
This is yet another instance of problems created by the double return path: `raft_apply` will call the callback with the error normally EXCEPT that when it already knows it is not the leader, then it will not and it will just return immediately without calling any callback.
This misdesign is plaguing this codebase and should be avoided in the future: only systematic errors like "wrong parameters" or "out of memory" should be returned immediately, **not** domain errors.
The fix for this specific bug is to route all errors through the state machine, so that now the state `EXEC_WAITING_APPLY` is not a phantom (trace-only) state anymore, but takes care of the required …

fix: always call `VfsAbort` on error

---

src/fsm.c
src/gateway.c
src/vfs.c
src/vfs.h
test/unit/test_vfs_extra.c

This PR follows up #811 and simplifies even more the snapshot interface by removing the always empty wal.
Please note that since #710 was merged before `v1.17.0` then this is compatible with any LTS version.

 refactor: remove wal from snapshot

---

src/vfs.c
test/unit/test_vfs.c

This PR fixes a bug introduced with #830 . Apparently, even if not documented, in-memory `sqlite3_file`s have a `NULL` `pMethods` field.
I added a test, just in case.

bugfix: allow opening in-memory databases
